apiVersion: v1
kind: Pod
metadata:
  name: pod-blue
  labels:
     app: web
spec:
  containers: 
    - name: blue
      image: kodekloud/webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: APP_COLOR
          value: "blue"